#!/bin/sh

FLIMSY_DIR="$HOME/.flimsy"

CLOJURES_DIR="$FLIMSY_DIR/clojures"
CLOJURE_LINK="$FLIMSY_DIR/clojure.jar"

[ -z $JAVA ] && JAVA="java"

# create the flimsy dir if it is not there
[ -d $FLIMSY_DIR ] || mkdir $FLIMSY_DIR

function usage {
	printf "flimsy <command> [options] [...]\n"
	printf "\n"
	printf "Where <command> can be:\n"
	printf "\thelp\t\t\t- Show this help message\n"
	printf "\tver|version\t\t- Show currently running clojure version\n"
	printf "\tlist\t\t\t- List all installed clojure versions\n"
	printf "\tinstall <version>\t- Install a given clojure version\n"
	printf "\tuse <version>\t\t- Use the given clojure version\n"
	printf "\trepl\t\t\t- Run REPL shell\n"
	printf "\trun <filename>\t\t- Run clojure file\n"
	printf "\n"
}

function clojure_version_from_path {
	basename $1 | awk '{ printf("%s", $sub(/.jar$/, "", $sub(/^clojure\-/, "", $0))) }'
}

function current_clojure_version {
	clojure_version_from_path $(readlink $CLOJURE_LINK)
}

function clojure_version {
	echo "clojure $(current_clojure_version)"
}

function clojures_list {
	running_version=$(current_clojure_version)

	for clojure in $CLOJURES_DIR/clojure-*.jar; do

		version=$(clojure_version_from_path $clojure)

		if [ "$version" = "$running_version" ]; then
			echo $version \*
		else
			echo $version
		fi
	done
}

function install_clojure {
	version=$1

	if [ -z $version ]; then
		echo "Please, specify a version such as '1.5.1'"
		exit 1
	fi

	clojure_jar="clojure-$version.jar"
	clojure_path="$CLOJURES_DIR/$clojure_jar"
	clojure_url="http://repo1.maven.org/maven2/org/clojure/clojure/$version/$clojure_jar"

	# create the clojures dir if it is not there
	[ -d $CLOJURES_DIR ] || mkdir $CLOJURES_DIR

	if [ -f $clojure_path ]; then
		echo "Clojure $version is already installed."
		echo "You can activate it with this command:"
		echo "flimsy use $version"
		exit 0
	fi

	exec wget -O $clojure_path $clojure_url
}

function use_clojure {
	version=$1

	if [ -z $version ]; then
		echo "Please, specify a version such as '1.5.1'"
		exit 1
	fi

	clojure_path="$CLOJURES_DIR/clojure-$version.jar"

	if ! [ -e $clojure_path ]; then
		echo "Clojure $version is not installed."
		echo "You can install it with this command:"
		echo "flimsy install $version"
		exit 1
	fi

	[ -e $CLOJURE_LINK ] && rm $CLOJURE_LINK

	exec ln -s $clojure_path $CLOJURE_LINK
}

function run_clojure {
	if ! [ -e $CLOJURE_LINK ]; then
		echo "You have not activated a particular version of Clojure"
		echo "You can use a pair of the 'install' and 'use' commands for this."
		exit 1
	fi

	exec $JAVA -cp $CLOJURE_LINK clojure.main "$@"
}

if [ $# -eq 0 ]; then
	usage
	exit 1
fi

case $1 in
	ver|version)
		clojure_version
		;;

	list)
		clojures_list
		;;

	install)
		install_clojure $2
		;;

	use)
		use_clojure $2
		;;

	repl)
		run_clojure
		;;

	run)
		shift
		run_clojure "$@"
		;;

	*|help)
		usage
		;;
esac

exit 0
